### PR TITLE
Node crash if tcp-initiator can't connect to server

### PR DESCRIPTION
**Pull request by hmvs**
Fix for #44

### CODE REVIEW

**Comment by hmvs** [comment]
Hmmm. It doesn't fix the issue fully. Let me debug further.

**Comment by hmvs** [comment]
Aha. We have some lost promise 
Error: StagingClient: timeout of 22 whilst connecting
    at /..../node_modules/jspurefix/src/transport/tcp/tcp-initiator.ts:183:20
[nodemon] app crashed - waiting for file changes before starting...

**Comment by hmvs** [comment]
The thing is. I open session only when it is needed. And right now we have some lost promise that crashes the whole app.

**Comment by TimelordUK** [comment]
Thanks for fix

**Pull request merged**
